kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    imagePullPolicy: Always
    repo: thangnvpixtavietnam/test-drone
    # tags: 
    #   - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
    auto_tag_suffix: 
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
    auto_tag: true
    username: thangnvpixtavietnam
    password: MyAVe58XvU2GoY