kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    imagePullPolicy: Always
    repo: thangnvpixtavietnam/test-drone
    tags: 
      - v1.0.${DRONE_BUILD_NUMBER}
      - latest
    cache_from: thangnvpixtavietnam/test-drone:latest
    username: thangnvpixtavietnam
    password: MyAVe58XvU2GoY