kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  environment:

  settings:
    imagePullPolicy: Always
    environment:
      - dronedate: 'date +%s'
    repo: thangnvpixtavietnam/test-drone
    tags: 
      - ${DRONE_BRANCH}-$(dronedate)
      - latest
    cache_from: thangnvpixtavietnam/test-drone:latest
    username: thangnvpixtavietnam
    password: MyAVe58XvU2GoY