apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: test-thangnv
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: thangnvpixtavietnam/test-drone:main-e12b2317b8875d4b8b34b9c7b6d151b555e5ebd1
        ports:
        - containerPort: 80