apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: test-thangnv
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: thangnvpixtavietnam/test-drone:main-200774756b94ccff6435829e8506266cb3842748
        ports:
        - containerPort: 80