apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nodejs
  namespace: test-thangnv
spec:
  image: thangnvpixtavietnam/test-drone
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nodejs
  namespace: test-thangnv
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: main*