apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  interval: 5s
  sourceRef:
    kind: GitRepository
    name: my-secrets
  path: ./sops
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg